---
name: ci-local-actionlint
run-name: Lint GitHub Workflows

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize, labeled]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: actionlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
